packages:
  - apps/*
  - packages/*

allowBuilds:
  "@swc/core": true
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true

minimumReleaseAgeExclude:
  - "@eslint-react/ast@5.8.5"
  - "@eslint-react/core@5.8.5"
  - "@eslint-react/eslint-plugin@5.8.5"
  - "@eslint-react/eslint@5.8.5"
  - "@eslint-react/jsx@5.8.5"
  - "@eslint-react/shared@5.8.5"
  - "@eslint-react/var@5.8.5"
  - eslint-plugin-react-dom@5.8.5
  - eslint-plugin-react-jsx@5.8.5
  - eslint-plugin-react-naming-convention@5.8.5
  - eslint-plugin-react-rsc@5.8.5
  - eslint-plugin-react-web-api@5.8.5
  - eslint-plugin-react-x@5.8.5

overrides:
  "@types/react": "~19.2.15"
  "@types/react-dom": "~19.2.3"
  "@vitest/coverage-v8": "4.1.7"
  "@vitest/runner": "4.1.7"
  "@vitest/spy": "4.1.7"
  react: "19.2.6"
  react-dom: "19.2.6"
  typescript: "~6.0.3"
  vitest: "4.1.7"
